import { useEffect, useMemo, useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

type Kind = "profiles" | "rooms" | "blogPosts" | "navigationItems" | "directorySections";
const kinds: { kind: Kind; label: string }[] = [
  { kind: "profiles", label: "Profiles" }, { kind: "rooms", label: "Rooms" }, { kind: "blogPosts", label: "Blog" }, { kind: "navigationItems", label: "Navigation" }, { kind: "directorySections", label: "Directory" },
];
const templates: Record<Kind, object> = {
  profiles: { username: "new-player", displayName: "New Player", bio: "", avatarUrl: "", bannerUrl: "", joinedAt: new Date().toISOString(), subscriberCount: 0, featured: false },
  rooms: { slug: "new-room", title: "New room", description: "", coverUrl: "", playerCount: 0, cheerCount: 0, featured: false },
  blogPosts: { title: "New story", slug: "new-story", body: "", author: "", category: "News", coverUrl: "", publishDate: new Date().toISOString(), published: false },
  navigationItems: { label: "New link", href: "/new-link", sortOrder: 5, visible: true },
  directorySections: { title: "New section", description: "", href: "/", sortOrder: 5, visible: true },
};

function BlogFields({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const data = (() => { try { return JSON.parse(value); } catch { return {}; } })();
  const set = (key: string, next: unknown) => onChange(JSON.stringify({ ...data, [key]: next }, null, 2));
  return <div className="mt-4 grid gap-4 md:grid-cols-2"><Input value={data.title || ""} onChange={e => set("title", e.target.value)} placeholder="Title" /><Input value={data.slug || ""} onChange={e => set("slug", e.target.value)} placeholder="Slug" /><Input value={data.category || ""} onChange={e => set("category", e.target.value)} placeholder="Category" /><Input value={data.author || ""} onChange={e => set("author", e.target.value)} placeholder="Author" /><Input type="datetime-local" value={data.publishDate ? new Date(data.publishDate).toISOString().slice(0, 16) : ""} onChange={e => set("publishDate", e.target.value ? new Date(e.target.value).toISOString() : null)} /><Input value={data.coverUrl || ""} onChange={e => set("coverUrl", e.target.value)} placeholder="Cover URL from media library" /><Textarea value={data.body || ""} onChange={e => set("body", e.target.value)} placeholder="Write the story body…" className="min-h-56 md:col-span-2" /></div>;
}

function parseBulkRooms(value: string) {
  const trimmed = value.trim();
  if (!trimmed) return [] as unknown[];
  try {
    const parsed = JSON.parse(trimmed) as unknown;
    if (Array.isArray(parsed)) return parsed;
    if (parsed && typeof parsed === "object" && Array.isArray((parsed as { rooms?: unknown[] }).rooms)) return (parsed as { rooms: unknown[] }).rooms;
  } catch {
    // Newline mode below accepts one room URL/slug per line.
  }
  return trimmed.split(/\r?\n/).map(line => line.trim()).filter(Boolean).map(line => {
    const slug = line.replace(/\/$/, "").split("/").pop() || line;
    return { slug, title: slug, sourceUrl: line.startsWith("http") ? line : `https://recroom.network/room/${slug}` };
  });
}

function AdminContent() {
  const { user } = useAuth();
  const [kind, setKind] = useState<Kind>("profiles");
  const [editor, setEditor] = useState<{ id?: number; value: string } | null>(null);
  const [mediaTarget, setMediaTarget] = useState<"avatarUrl" | "bannerUrl" | "coverUrl">("avatarUrl");
  const [account, setAccount] = useState({ username: "", displayName: "", password: "", role: "user" as "user" | "admin", avatarUrl: "" });
  const [settingsForm, setSettingsForm] = useState({ announcementText: "", announcementLink: "", announcementVisible: true, featuredRoomSlugs: [] as string[] });
  const [bulkText, setBulkText] = useState("");
  const [bulkRows, setBulkRows] = useState<unknown[]>([]);
  const utils = trpc.useUtils();
  const list = trpc.admin.list.useQuery({ kind });
  const roomsForSettings = trpc.rooms.list.useQuery();
  const media = trpc.media.list.useQuery();
  const accounts = trpc.managedAccounts.list.useQuery();
  const settings = trpc.settings.admin.useQuery();
  const updateSettings = trpc.settings.update.useMutation({ onSuccess: () => { toast.success("Announcement and featured rooms saved"); utils.settings.admin.invalidate(); utils.settings.public.invalidate(); }, onError: error => toast.error(error.message) });
  const bulkInput = useMemo(() => ({ rooms: bulkRows }), [bulkRows]);
  const bulkPreview = trpc.admin.bulkRoomPreview.useQuery(bulkInput, { enabled: bulkRows.length > 0 });
  const bulkImport = trpc.admin.bulkRoomImport.useMutation({ onSuccess: result => { toast.success(`Imported ${result.imported} rooms and ${result.photosImported} room photos`); setBulkText(""); setBulkRows([]); bulkPreview.refetch(); utils.admin.list.invalidate({ kind: "rooms" }); utils.rooms.list.invalidate(); }, onError: error => toast.error(error.message) });
  const syncStatus = trpc.admin.syncStatus.useQuery();
  const syncNow = trpc.admin.syncNow.useMutation({ onSuccess: result => { toast.success(`Sync discovered ${result.discovered} rooms`); syncStatus.refetch(); utils.admin.list.invalidate({ kind: "rooms" }); utils.rooms.list.invalidate(); }, onError: error => toast.error(error.message) });
  const create = trpc.admin.create.useMutation({ onSuccess: () => { toast.success("Created"); setEditor(null); utils.admin.list.invalidate({ kind }); }, onError: error => toast.error(error.message) });
  const update = trpc.admin.update.useMutation({ onSuccess: () => { toast.success("Saved"); setEditor(null); utils.admin.list.invalidate({ kind }); }, onError: error => toast.error(error.message) });
  const remove = trpc.admin.delete.useMutation({ onSuccess: () => { toast.success("Deleted"); utils.admin.list.invalidate({ kind }); }, onError: error => toast.error(error.message) });
  const upload = trpc.media.upload.useMutation({ onSuccess: () => { toast.success("Uploaded to photo library"); utils.media.list.invalidate(); }, onError: error => toast.error(error.message) });
  const deleteMedia = trpc.media.delete.useMutation({ onSuccess: () => { toast.success("Removed from library"); utils.media.list.invalidate(); }, onError: error => toast.error(error.message) });
  const createAccount = trpc.managedAccounts.create.useMutation({ onSuccess: () => { toast.success("Account created"); setAccount({ username: "", displayName: "", password: "", role: "user", avatarUrl: "" }); utils.managedAccounts.list.invalidate(); }, onError: error => toast.error(error.message) });
  const deleteAccount = trpc.managedAccounts.delete.useMutation({ onSuccess: () => { toast.success("Account removed"); utils.managedAccounts.list.invalidate(); }, onError: error => toast.error(error.message) });
  const rows = list.data || [];
  useEffect(() => { if (!settings.data) return; let featuredRoomSlugs: string[] = []; try { featuredRoomSlugs = JSON.parse(settings.data.featuredRoomSlugs) as string[]; } catch { featuredRoomSlugs = []; } setSettingsForm({ announcementText: settings.data.announcementText, announcementLink: settings.data.announcementLink || "", announcementVisible: settings.data.announcementVisible, featuredRoomSlugs }); }, [settings.data]);
  const title = useMemo(() => kinds.find(item => item.kind === kind)?.label, [kind]);
  const uploadFile = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const data = btoa(String.fromCharCode(...Array.from(new Uint8Array(await file.arrayBuffer())))); upload.mutate({ filename: file.name, contentType: file.type || "application/octet-stream", data }); event.currentTarget.value = ""; };
  const applyMedia = (url: string, field: "avatarUrl" | "bannerUrl" | "coverUrl") => { if (!editor) { navigator.clipboard?.writeText(url); toast.success("Media URL copied"); return; } try { const current = JSON.parse(editor.value); setEditor({ ...editor, value: JSON.stringify({ ...current, [field]: url }, null, 2) }); toast.success(`Applied to ${field}`); } catch { toast.error("Open an editor before applying media"); } };
  if (!user) return null;
  if (user.role !== "admin") return <div className="mx-auto max-w-xl rounded-3xl border border-red-400/20 bg-red-400/10 p-8"><h1 className="text-2xl font-black">Admin access required</h1><p className="mt-3 text-white/65">Your account is authenticated, but it does not have the admin role.</p></div>;
  return <div className="admin-panel space-y-6">
    <div className="flex flex-col justify-between gap-4 border-b border-white/10 pb-5 md:flex-row md:items-end"><div><div className="eyebrow">CONTENT CONTROL</div><h1 className="text-3xl font-black">Editable hub</h1></div><Button onClick={() => setEditor({ value: JSON.stringify(templates[kind], null, 2) })} className="bg-[#ff9b62] text-[#251714] hover:bg-[#ffb58f]">Create {title}</Button></div>
    <section className="rounded-2xl border border-[#ff9b62]/30 bg-[#211b20] p-5"><div className="eyebrow">HOMEPAGE CONTROLS</div><h2 className="mt-1 text-xl font-black">Announcement & Featured Rooms</h2><div className="mt-4 grid gap-3"><Textarea value={settingsForm.announcementText} onChange={e => setSettingsForm({ ...settingsForm, announcementText: e.target.value })} placeholder="Announcement text" className="min-h-24 border-white/10 bg-black/20" /><Input value={settingsForm.announcementLink} onChange={e => setSettingsForm({ ...settingsForm, announcementLink: e.target.value })} placeholder="Announcement link (optional)" /><label className="flex items-center gap-2 text-sm text-white/70"><input type="checkbox" checked={settingsForm.announcementVisible} onChange={e => setSettingsForm({ ...settingsForm, announcementVisible: e.target.checked })} /> Show announcement strip</label><div><p className="text-sm font-bold">Featured room order</p><p className="mt-1 text-xs text-white/40">Select rooms from the imported room list and arrange them in homepage order.</p><div className="mt-3 grid gap-2 md:grid-cols-2">{(roomsForSettings.data || []).map((room: any) => { const selected = settingsForm.featuredRoomSlugs.includes(room.slug); return <label key={room.slug} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-sm ${selected ? "border-[#ff9b62]/50 bg-[#ff9b62]/10" : "border-white/10 bg-black/10"}`}><input type="checkbox" checked={selected} onChange={() => setSettingsForm({ ...settingsForm, featuredRoomSlugs: selected ? settingsForm.featuredRoomSlugs.filter(slug => slug !== room.slug) : [...settingsForm.featuredRoomSlugs, room.slug] })} /><span className="truncate">^{room.title}</span></label>; })}</div><div className="mt-3 flex flex-wrap gap-2">{settingsForm.featuredRoomSlugs.map((slug, index) => <button type="button" key={slug} onClick={() => setSettingsForm({ ...settingsForm, featuredRoomSlugs: settingsForm.featuredRoomSlugs.filter(item => item !== slug).concat(slug) })} className="rounded-full bg-[#ff9b62]/15 px-3 py-1 text-xs text-[#ffc3a6]">{index + 1}. {slug}</button>)}</div></div><Button onClick={() => updateSettings.mutate(settingsForm)} disabled={updateSettings.isPending || !settingsForm.announcementText.trim()} className="w-fit bg-[#ff9b62] text-[#251714]">Save homepage controls</Button></div></section>
    <section className="rounded-2xl border border-white/10 bg-[#1b171d] p-5"><div className="eyebrow">AUTOMATIC ROOM SYNC</div><h2 className="mt-1 text-xl font-black">30-minute room discovery</h2><p className="mt-2 max-w-3xl text-sm text-white/55">The scheduled worker will discover public room links, add new link-only records, preserve existing metadata, and deduplicate room photos. The live schedule stays disabled until the site is deployed and the callback is registered.</p><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-white/5 p-3"><span className="block text-xs uppercase tracking-wider text-white/35">Schedule</span><strong className="mt-1 block">{syncStatus.data?.syncCron || "0 */30 * * * *"}</strong></div><div className="rounded-xl bg-white/5 p-3"><span className="block text-xs uppercase tracking-wider text-white/35">Status</span><strong className="mt-1 block">{syncStatus.data?.syncLastStatus || "Not run"}</strong></div><div className="rounded-xl bg-white/5 p-3"><span className="block text-xs uppercase tracking-wider text-white/35">Imported last run</span><strong className="mt-1 block">{syncStatus.data?.syncLastImported ?? 0} rooms / {syncStatus.data?.syncLastPhotos ?? 0} photos</strong></div><div className="rounded-xl bg-white/5 p-3"><span className="block text-xs uppercase tracking-wider text-white/35">Last run</span><strong className="mt-1 block">{syncStatus.data?.syncLastRunAt ? new Date(syncStatus.data.syncLastRunAt).toLocaleString() : "Never"}</strong></div></div>{syncStatus.data?.syncLastError && <p className="mt-3 rounded-lg bg-red-400/10 p-3 text-xs text-red-200">{syncStatus.data.syncLastError}</p>}<Button onClick={() => syncNow.mutate()} disabled={syncNow.isPending} variant="outline" className="mt-4">{syncNow.isPending ? "Running sync…" : "Run sync now"}</Button></section>
    <section className="rounded-2xl border border-[#ff9b62]/30 bg-[#211b20] p-5"><div className="eyebrow">BULK ROOM IMPORT</div><h2 className="mt-1 text-xl font-black">Add multiple rooms at once</h2><p className="mt-2 max-w-3xl text-sm text-white/55">Paste a JSON array of room objects, a JSON object containing a rooms array, or one public room URL/slug per line. Preview checks slugs and fields before persistence; existing slugs are reported and updated if imported.</p><Textarea value={bulkText} onChange={e => setBulkText(e.target.value)} placeholder={'https://recroom.network/room/NewRoom\\nhttps://recroom.network/room/AnotherRoom'} className="mt-4 min-h-32 border-white/10 bg-black/20 font-mono text-xs" /><div className="mt-3 flex flex-wrap gap-2"><Button onClick={() => { const rows = parseBulkRooms(bulkText); setBulkRows(rows); if (!rows.length) toast.error("Paste at least one room URL or JSON record"); }} disabled={!bulkText.trim()} className="bg-[#ff9b62] text-[#251714]">Preview rooms</Button>{bulkPreview.data && <Button onClick={() => bulkImport.mutate({ rooms: bulkPreview.data.valid })} disabled={bulkImport.isPending || !bulkPreview.data.valid.length} variant="outline">Import {bulkPreview.data.valid.length} valid rooms</Button>}</div>{bulkPreview.data && <div className="mt-4 grid gap-3 text-sm md:grid-cols-3"><div className="rounded-xl bg-emerald-400/10 p-3"><strong className="block text-emerald-200">{bulkPreview.data.valid.length} valid</strong><span className="text-white/45">Ready to import</span></div><div className="rounded-xl bg-amber-400/10 p-3"><strong className="block text-amber-200">{bulkPreview.data.duplicates.length} duplicates</strong><span className="text-white/45">Existing slugs will update</span></div><div className="rounded-xl bg-red-400/10 p-3"><strong className="block text-red-200">{bulkPreview.data.invalid.length} invalid</strong><span className="text-white/45">Excluded from import</span></div></div>}{bulkPreview.data?.invalid.length ? <div className="mt-3 rounded-xl border border-red-300/20 bg-red-400/5 p-3 text-xs text-red-100">{bulkPreview.data.invalid.slice(0, 12).map(item => <p key={item.index}>Row {item.index + 1}: {item.errors.join("; ")}</p>)}</div> : null}</section>
    <div className="flex flex-wrap gap-2">{kinds.map(item => <button key={item.kind} onClick={() => { setKind(item.kind); setEditor(null); }} className={`rounded-full px-4 py-2 text-sm font-bold transition ${kind === item.kind ? "bg-[#ff9b62] text-[#251714]" : "bg-white/5 text-white/60 hover:bg-white/10"}`}>{item.label}</button>)}</div>
    <section className="rounded-2xl border border-white/10 bg-[#1b171d] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Photo library</h2><p className="mt-1 text-xs text-white/40">Upload, browse, apply, or remove photo assets. Removing a record does not attempt to delete the underlying S3 object.</p>{kind === "profiles" && <div className="mt-3 flex gap-2"><button type="button" onClick={() => setMediaTarget("avatarUrl")} className={`rounded-full px-3 py-1 text-xs font-bold ${mediaTarget === "avatarUrl" ? "bg-[#ff9b62] text-[#251714]" : "bg-white/10 text-white/55"}`}>Apply to avatar</button><button type="button" onClick={() => setMediaTarget("bannerUrl")} className={`rounded-full px-3 py-1 text-xs font-bold ${mediaTarget === "bannerUrl" ? "bg-[#ff9b62] text-[#251714]" : "bg-white/10 text-white/55"}`}>Apply to banner</button></div>}</div><label className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold hover:bg-white/15">Upload photo<input type="file" accept="image/*" className="hidden" onChange={uploadFile} /></label></div></section>
    {media.data?.length ? <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{media.data.map(asset => <div key={asset.id} className="overflow-hidden rounded-xl border border-white/10 bg-white/5"><img src={asset.url} alt={asset.filename} className="aspect-video w-full object-cover" /><div className="p-2"><span className="block truncate text-xs text-white/55">{asset.filename}</span><div className="mt-2 flex flex-wrap gap-1"><button type="button" onClick={() => applyMedia(asset.url, kind === "profiles" ? mediaTarget : "coverUrl")} className="rounded bg-white/10 px-2 py-1 text-[10px] font-bold">Apply</button><button type="button" onClick={() => setAccount({ ...account, avatarUrl: asset.url })} className="rounded bg-white/10 px-2 py-1 text-[10px] font-bold">Account avatar</button><button type="button" onClick={() => deleteMedia.mutate({ id: asset.id })} className="rounded bg-red-400/15 px-2 py-1 text-[10px] font-bold text-red-200">Delete</button></div></div></div>)}</section> : <div className="rounded-xl border border-dashed border-white/15 p-5 text-sm text-white/45">No uploaded photos yet.</div>}
    <section className="rounded-2xl border border-white/10 bg-[#1b171d] p-5"><h2 className="font-bold">Create password account</h2><p className="mt-1 text-xs text-white/40">Passwords are hashed with scrypt. The configured bootstrap value is never shown or stored in plaintext.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Input value={account.username} onChange={e => setAccount({ ...account, username: e.target.value })} placeholder="Username" /><Input value={account.displayName} onChange={e => setAccount({ ...account, displayName: e.target.value })} placeholder="Display name" /><Input type="password" value={account.password} onChange={e => setAccount({ ...account, password: e.target.value })} placeholder="Password (8+ characters)" /><select value={account.role} onChange={e => setAccount({ ...account, role: e.target.value as "user" | "admin" })} className="rounded-md border border-white/10 bg-black/20 px-3 text-sm"><option value="user">User</option><option value="admin">Admin</option></select></div><div className="mt-3 flex items-center gap-3">{account.avatarUrl && <img src={account.avatarUrl} alt="Selected avatar" className="h-12 w-12 rounded-full object-cover" />}<span className="text-xs text-white/45">{account.avatarUrl ? "Avatar selected from the photo library." : "Choose Account avatar on any uploaded photo above."}</span></div><Button onClick={() => createAccount.mutate(account)} disabled={!account.username || !account.displayName || account.password.length < 8} className="mt-4 bg-[#ff9b62] text-[#251714]">Create account</Button><div className="mt-5 divide-y divide-white/10">{accounts.data?.map(item => <div key={item.id} className="flex items-center justify-between gap-3 py-3"><div className="flex items-center gap-3">{item.avatarUrl ? <img src={item.avatarUrl} alt="" className="h-9 w-9 rounded-full object-cover" /> : <div className="h-9 w-9 rounded-full bg-white/10" />}<div><p className="text-sm font-bold">{item.displayName}</p><p className="text-xs text-white/45">@{item.username} · {item.role}</p></div></div><Button variant="destructive" size="sm" onClick={() => deleteAccount.mutate({ id: item.id })}>Delete</Button></div>)}</div></section>
    {editor && <section className="rounded-2xl border border-[#ff9b62]/30 bg-[#211b20] p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{editor.id ? "Edit" : "Create"} {title}</h2><button onClick={() => setEditor(null)} className="text-white/40">Close</button></div>{kind === "blogPosts" ? <BlogFields value={editor.value} onChange={value => setEditor({ ...editor, value })} /> : <Textarea value={editor.value} onChange={e => setEditor({ ...editor, value: e.target.value })} className="mt-4 min-h-64 border-white/10 bg-black/20 font-mono text-xs" />}<div className="mt-4 flex gap-3"><Button onClick={() => { try { const data = JSON.parse(editor.value); if (kind === "rooms" && (typeof data.slug !== "string" || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(data.slug))) { toast.error("Room slug must use lowercase letters, numbers, and hyphens"); return; } editor.id ? update.mutate({ kind, id: editor.id, data }) : create.mutate({ kind, data }); } catch { toast.error("Use valid JSON"); } }} className="bg-[#ff9b62] text-[#251714]">Save</Button><Button variant="ghost" onClick={() => setEditor(null)}>Cancel</Button></div></section>}
    <section className="overflow-hidden rounded-2xl border border-white/10 bg-[#1b171d]"><div className="border-b border-white/10 px-5 py-4 text-sm font-bold text-white/60">{rows.length} {title} records</div>{list.isLoading ? <div className="p-8 text-white/45">Loading records…</div> : rows.length ? <div className="divide-y divide-white/10">{rows.map((row: any) => <div key={row.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="truncate font-semibold">{row.title || row.displayName || row.label || row.username || `Record #${row.id}`}</p><p className="truncate text-xs text-white/35">{row.slug || row.href || row.username || `ID ${row.id}`}</p></div><div className="flex shrink-0 gap-2"><Button variant="outline" size="sm" onClick={() => setEditor({ id: row.id, value: JSON.stringify(row, null, 2) })}>Edit</Button><Button variant="destructive" size="sm" onClick={() => { if (confirm("Delete this record?")) remove.mutate({ kind, id: row.id }); }}>Delete</Button></div></div>)}</div> : <div className="p-8 text-white/45">No records yet.</div>}</section>
  </div>;
}
export default function Admin() { return <DashboardLayout><AdminContent /></DashboardLayout>; }
